=== easitab/PSImportClient/schemas/psImportClientSettings.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "PSImportClient settings",
  "description": "Schema for PSImportClient settings file",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "defaultModules": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "dependencyModules": {
      "type": "object",
      "properties": {
        "jdbcConfiguration": {
          "type": "string"
        }
      },
      "required": [
        "jdbcConfiguration"
      ]
    },
    "notificationSettings": {
      "type": "object",
      "properties": {
        "enabled": {
          "type": "boolean"
        },
        "type": {
          "type": "string"
        },
        "SmtpServer": {
          "type": "string"
        },
        "Port": {
          "type": "number"
        },
        "To": {
          "type": "string"
        },
        "From": {
          "type": "string"
        },
        "Subject": {
          "type": "string"
        },
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        }
      },
      "required": [
        "enabled",
        "type",
        "SmtpServer",
        "Port",
        "To",
        "From",
        "Subject",
        "username",
        "password"
      ]
    },
    "loggerSettings": {
      "type": "object",
      "properties": {
        "LoggingLevel": {
          "type": "string"
        },
        "LogName": {
          "type": "string"
        },
        "LogDirectory": {
          "type": "string"
        },
        "RotationInterval": {
          "type": "number"
        },
        "LogNonOkImportResults": {
          "type": "boolean"
        }
      },
      "required": [
        "LoggingLevel",
        "LogName",
        "LogDirectory",
        "RotationInterval"
      ]
    },
    "archiveSettings": {
      "type": "object",
      "properties": {
        "directory": {
          "type": "string"
        },
        "rotationInterval": {
          "type": "number"
        }
      },
      "required": [
        "directory",
        "rotationInterval"
      ]
    }
  },
  "required": [
    "defaultModules",
    "dependencyModules",
    "loggerSettings",
    "archiveSettings"
  ]
}

=== easitab/PSImportClient/PSImportClientSettings.example.json
{
    "$schema": "schemas\\psImportClientSettings.schema.json",
    "defaultModules":[
        "Easit.PSImportClient.Commons",
        "Easit.GO.Webservice"
    ],
    "dependencyModules":{
        "jdbcConfiguration":"Easit.PSImportClient.Jdbc"
    },
    "notificationSettings": {
        "enabled": false,
        "type":"smtp",
        "SmtpServer": "",
        "Port": 993,
        "To": "",
        "From": "",
        "Subject": "",
        "username" : "",
        "password" : ""
    },
    "loggerSettings": {
        "LoggingLevel": "DEBUG",
        "LogName": "psImportClient",
        "LogDirectory": "logs",
        "RotationInterval": 30,
        "LogNonOkImportResults":true
    },
	"archiveSettings": {
		"directory":"archive",
		"rotationInterval":30
	}
}
